ALTER TABLE public.attachments
  ADD COLUMN IF NOT EXISTS entity_id int DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS storage_key text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS storage_kind int DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS creator_user_id text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS length_bytes bigint DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS file_name text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS mime_type text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS has_preview boolean DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS is_gzip_compressed boolean DEFAULT NULL;