services:
  postgres:
    container_name: postgres_bugget
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ../../migrator/sql:/docker-entrypoint-initdb.d
