services:
  frontend_bugget:
    container_name: frontend_bugget
    image: ${FRONTEND_IMAGE:-gently4005/bugget-ui:latest}
    build:
      context: ${FRONTEND_BUILD_CONTEXT:-}
      dockerfile: ${FRONTEND_DOCKERFILE:-}
    ports:
      - "80:80"
    restart: unless-stopped