FROM mcr.microsoft.com/dotnet/sdk:9.0.100-alpine3.20 AS build
WORKDIR /app

COPY . ./
COPY Migrations ./scripts
RUN dotnet restore

RUN dotnet publish -c Release -o /out

FROM mcr.microsoft.com/dotnet/runtime:9.0
WORKDIR /app

COPY --from=build /out ./

COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh