---
#-----------------------------------------------------------------------------------------
#
# Публикация bugget-migrator
#
#-----------------------------------------------------------------------------------------

name: publish-migrator
description: "Сборка и публикация bugget-migrator в Docker Hub"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Версия (например, v1.2.3)"
        required: true

jobs:
  migrator:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set version
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Migrator Multi-Arch
        run: |
          cd devops/migrator
          docker buildx create --name mybuilder --use --bootstrap || docker buildx use mybuilder
          docker buildx inspect mybuilder --bootstrap
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            -t ${{ secrets.DOCKER_LOGIN }}/bugget-migrator:${{ env.VERSION }} \
            --push \
            -f ./Dockerfile .
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            -t ${{ secrets.DOCKER_LOGIN }}/bugget-migrator:latest \
            --push \
            -f ./Dockerfile .
